version: '2'
services:
    21point-app:
        image: 21point
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://21point-postgresql:5432/21point
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://21point-elasticsearch:9200
        ports:
            - 8080:8080
    21point-postgresql:
        extends:
            file: postgresql.yml
            service: 21point-postgresql
    21point-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: 21point-elasticsearch
